"""Added admin column

Revision ID: 4372993895f3
Revises: 
Create Date: 2026-06-25 17:47:48.764453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4372993895f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column(
        'is_admin',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
